name: Test workflow
on: push
jobs:
  lint:
    name: Lint sources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: "actions/checkout@main"
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install foundry dependencies
        run: forge install
      - name: Create a fake .secret file
        run: echo "primary twist rack vendor diagram image used route theme frown either will" > .secret
      - name: Install hardhat dependencies
        run: yarn install --frozen-lockfile && yarn build
      - name: Lint sources
        run: yarn run lint

  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: "actions/checkout@main"

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create a fake .secret file
        run: echo "primary twist rack vendor diagram image used route theme frown either will" > .secret

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install foundry dependencies
        run: forge install

      - name: Install hardhat dependencies
        run: yarn install --frozen-lockfile && yarn build

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: forge-build
        
      - name: Go to account-abstraction directory
        run: cd lib/account-abstraction

      - name: Install typechain dependencies
        run: yarn install

      - name: Generate Typechain typings
        run: npx hardhat typechain

      - name: Return to project root
        run: cd ../..

      - name: Run Hardhat Tests
        run: yarn test

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test
